-- Расширение схемы: сертификаты (одноразовость по telegram_id + code) и история бонусов.
-- Применять к PostgreSQL (FastAPI / python_api).

BEGIN;

CREATE TABLE IF NOT EXISTS certificate_redemptions (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id     bigint NOT NULL,
    code            varchar(64) NOT NULL,
    order_id        integer NULL REFERENCES orders(id) ON DELETE SET NULL,
    redeemed_at     timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_certificate_redemption UNIQUE (telegram_id, code)
);

CREATE INDEX IF NOT EXISTS idx_certificate_redemptions_tg ON certificate_redemptions (telegram_id);

-- Текущая «активация» в интерфейсе до оформления заказа (одна на пользователя).
CREATE TABLE IF NOT EXISTS certificate_pending (
    telegram_id      bigint PRIMARY KEY,
    code             varchar(64) NOT NULL,
    discount_percent numeric(5, 2) NOT NULL,
    updated_at       timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bonus_ledger (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id  bigint NULL,
    user_id      integer NULL REFERENCES users(id) ON DELETE SET NULL,
    order_id     integer NULL REFERENCES orders(id) ON DELETE SET NULL,
    order_number varchar(50) NULL,
    entry_type   varchar(16) NOT NULL,
    amount       integer NOT NULL,
    note         text NULL,
    created_at   timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_bonus_ledger_type CHECK (entry_type IN ('earn', 'spend'))
);

CREATE INDEX IF NOT EXISTS idx_bonus_ledger_tg ON bonus_ledger (telegram_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bonus_ledger_user ON bonus_ledger (user_id, created_at DESC);

COMMIT;
