-- PC Salon optimized PostgreSQL schema
-- Compatible with current FastAPI backend (python_api/main.py)

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id     bigint UNIQUE,
    first_name      varchar(100),
    last_name       varchar(100),
    username        varchar(100),
    phone           varchar(20),
    full_name       varchar(255),
    address         text,
    created_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_users_phone_len CHECK (phone IS NULL OR char_length(phone) BETWEEN 6 AND 20)
);

CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users (telegram_id);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at DESC);

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS categories (
    id              varchar(50) PRIMARY KEY,
    name            varchar(100) NOT NULL,
    image           varchar(255),
    display_order   integer NOT NULL DEFAULT 0,
    created_at      timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_categories_display_order ON categories (display_order, id);

CREATE TABLE IF NOT EXISTS products (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     varchar(50) NOT NULL,
    name            varchar(255) NOT NULL,
    price           numeric(10, 2) NOT NULL,
    image           varchar(255),
    cpu             varchar(100),
    gpu             varchar(100),
    description     text,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT chk_products_price_nonnegative CHECK (price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON products (is_active);
CREATE INDEX IF NOT EXISTS idx_products_category_active ON products (category_id, is_active, id);
CREATE INDEX IF NOT EXISTS idx_products_active_only ON products (id) WHERE is_active = true;

DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS orders (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NULL,
    order_number    varchar(50) UNIQUE NOT NULL,
    delivery_type   varchar(20) NOT NULL,
    full_name       varchar(255) NOT NULL,
    phone           varchar(20) NOT NULL,
    address         text,
    comment         text,
    total_amount    numeric(10, 2) NOT NULL,
    payment_method  varchar(20) NOT NULL DEFAULT 'cash',
    payment_status  varchar(20) NOT NULL DEFAULT 'pending',
    order_status    varchar(20) NOT NULL DEFAULT 'new',
    created_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_orders_delivery_type CHECK (delivery_type IN ('delivery', 'pickup')),
    CONSTRAINT chk_orders_payment_method CHECK (payment_method IN ('card', 'cash')),
    CONSTRAINT chk_orders_payment_status CHECK (payment_status IN ('pending', 'paid', 'failed')),
    CONSTRAINT chk_orders_order_status CHECK (order_status IN ('new', 'processing', 'confirmed', 'shipped', 'delivered', 'cancelled')),
    CONSTRAINT chk_orders_total_amount_nonnegative CHECK (total_amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders (order_number);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (order_status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_phone_created ON orders (phone, created_at DESC);

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS order_items (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        integer NOT NULL,
    product_id      integer NULL,
    item_type       varchar(20) NOT NULL DEFAULT 'product',
    item_name       varchar(255) NOT NULL,
    item_specs      text,
    quantity        integer NOT NULL DEFAULT 1,
    unit_price      numeric(10, 2) NOT NULL,
    total_price     numeric(10, 2) NOT NULL,
    config_data     jsonb NULL,
    created_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT chk_order_items_type CHECK (item_type IN ('product', 'config', 'pc')),
    CONSTRAINT chk_order_items_qty_positive CHECK (quantity > 0),
    CONSTRAINT chk_order_items_unit_price_nonnegative CHECK (unit_price >= 0),
    CONSTRAINT chk_order_items_total_price_nonnegative CHECK (total_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_created ON order_items (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_config_data_gin ON order_items USING GIN (config_data);

CREATE TABLE IF NOT EXISTS reviews (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NULL,
    order_id        integer NULL,
    product_id      integer NULL,
    rating          smallint NOT NULL,
    title           varchar(255),
    comment         text,
    is_published    boolean NOT NULL DEFAULT false,
    created_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    updated_at      timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_reviews_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX IF NOT EXISTS idx_reviews_published ON reviews (is_published);
CREATE INDEX IF NOT EXISTS idx_reviews_product ON reviews (product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews (user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_created ON reviews (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_product_published_created ON reviews (product_id, is_published, created_at DESC);

DROP TRIGGER IF EXISTS trg_reviews_updated_at ON reviews;
CREATE TRIGGER trg_reviews_updated_at
BEFORE UPDATE ON reviews
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;
